name: Build

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22
          cache: npm

      - run: npm ci

      - run: npm audit --audit-level=moderate

      - run: npm run lint

      - run: npm run format:check

      - run: npm run check

      - run: npm run build

      - name: Check internal links
        uses: lycheeverse/lychee-action@8646ba30535128ac92d33dfc9133794bfdd9b411 # v2.8.0
        with:
          args: >-
            --offline
            --include-fragments
            --root-dir "${{ github.workspace }}/dist"
            ./dist
          fail: true

  lighthouse:
    name: Lighthouse
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22
          cache: npm

      - run: npm ci

      - run: npm run build

      - uses: treosh/lighthouse-ci-action@3e7e23fb74242897f95c0ba9cabad3d0227b9b18 # v12.6.2
        with:
          configPath: ./lighthouserc.json
          uploadArtifacts: true
